[Bugfix][Android] Prevent empty notifications when receiving Firebase data messages
wix/react-native-notifications pull request #595
Opened 2020-04-29 05:17 UTC by Robfz

## Current behavior
When receiving Firebase data messages (messages without `title` or `body`), an empty notification is shown.

## New behavior
When receiving  Firebase data messages, the notification is only handled by JS and no notification is shown.

### Other changes
- Tests for the changes above.
- Fixed a duplicated test that wasn't testing what it should (`onReceived_validDataForBackgroundApp_postNotificationAndNotifyJs`)

2020-05-21 20:40 UTC, Robfz commented
@yogevbd is there any feedback on this, or is there anything I could do to drive this PR forward? Thanks.

2020-07-07 17:13 UTC, douira commented
why is this marked as stale if the maintainers have just not looked at it yet

2020-07-22 19:10 UTC, CesarLanderos commented
@yogevbd can we move this forward please? 🙏 , we are kind of blocked, we also want to push other fixes but we have seen no activity in this PR for so many months that we feel a little bit discouraged, this is the best library that we have found and we very much like to contribute to make it even better 🙏

2020-09-22 08:10 UTC, yogevbd approved these changes

2020-09-22 08:10 UTC, yogevbd commented on package.json
> +  "name": "@hiretend/react-native-notifications",
```suggestion
  "name": "react-native-notifications",
```

2020-09-22 08:10 UTC, yogevbd commented on package.json
> +    "registry": "https://npm.pkg.github.com/"
```suggestion
    "registry": "https://registry.npmjs.org/"
```

2020-09-22 08:10 UTC, yogevbd commented on package.json
> +    "url": "ssh://git@github.com/hiretend/react-native-notifications.git"
```suggestion
    "url": "https://github.com/wix/react-native-notifications.git"
```

2020-09-22 08:18 UTC, yogevbd requested changes

2020-09-22 08:18 UTC, yogevbd commented on package.json
> +  "name": "@hiretend/react-native-notifications",
```suggestion
  "name": "react-native-notifications",
```

2020-09-22 08:18 UTC, yogevbd commented on package.json
> +    "registry": "https://npm.pkg.github.com/"
```suggestion
    "registry": "https://registry.npmjs.org/"
```

2020-09-22 08:18 UTC, yogevbd commented on package.json
> +    "url": "ssh://git@github.com/hiretend/react-native-notifications.git"
```suggestion
    "url": "https://github.com/wix/react-native-notifications.git"
```

2020-09-22 23:37 UTC, Robfz commented
@yogevbd sorry about the extra commits! We made further changes to our fork. I created a fresh PR with only the changes related to this bug (https://github.com/wix/react-native-notifications/pull/677). Thanks for reviewing!

2020-09-22 23:37 UTC, closed without merging